## YAML Template.
---
name: Maven Package

on:
  release:
    types: [created]
  push:
  pull_request:


jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        ##settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Unit Tests with Maven
      run: mvn test
    - name: upload UT
      uses: actions/upload-artifact@v3
      with:
        name: com.medhead.api.repository.HospitalRepositoryCustomTest.txt com.medhead.api.service.HospitalServiceTest.txt
        path: target/surefire-reports
    - name: Integration Tests with Maven
      run: mvn failsafe:integration-test
    - name: upload IT
      uses: actions/upload-artifact@v3
      with:
        name: failsafe-summary.xml
        path: target/failsafe-reports

  build:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: get env dir
        run: pwd && ls -ltr target/ #/home/runner/work/ms1/ms1/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pocApiMedHead-0.0.1-SNAPSHOT-v${{github.run_number}}.jar
          path: target/
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
      ## - name: Publish package
     ##   run: mvn --batch-mode -DskipTests -DuseGitHubPackages=true deploy
     ##   env:
     ##     GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pocApiMedHead-0.0.1-SNAPSHOT-v${{github.run_number}}.jar
      - name: get env dir
        run: pwd && ls -ltr
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: etcomment/ms1:v${{github.run_number}}
          context: .
      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: etcomment/ms1:latest
          context: .