## YAML Template.
---
name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ "TestingImpl" ]
  pull_request:
    branches: [ "TestingImpl" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        ##settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Tests with Maven
      run: mvn test

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: get env dir
      run: pwd && ls -ltr target/ #/home/runner/work/ms1/ms1/
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
       name: pocApiMedHead-0.0.1-SNAPSHOT.war
       path: target/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
      ## - name: Publish package
     ##   run: mvn --batch-mode -DskipTests -DuseGitHubPackages=true deploy
     ##   env:
     ##     GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pocApiMedHead-0.0.1-SNAPSHOT.war
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: etcomment/ms1:v${{github.run_number}}